version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodbypm
    ports:
      - 27017-27019:27017-27019
    volumes:
      - data:/data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=application
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-expressypm
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongodb_network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=mongodb://rootuser:rootpass@mongodb:27017/application
      - SPRING_DATASOURCE_USERNAME=rootuser
      - SPRING_DATASOURCE_PASSWORD=rootpass
    depends_on:
      - mongodb
    networks:
      - mongodb_network

volumes:
  data: { }

networks:
  mongodb_network:
    external: true