version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb2
    ports:
      - 27017-27019:27017-27019
    volumes:
      - data:/data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=application
  mongo-express:
    image: mongo-express
    container_name: mongo-express3
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: { }
networks:
  default:
    name: mongodb_network