name: Docker Image CI

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2 
      
      - name: Setup Java JDK
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with: 
          maven-version: 3.8.2
      
      - name: Build JAR
        run: mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
        
      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up -d
      
      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/YPM:latest
        
